import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1759546443941 implements MigrationInterface {
    name = 'Initial1759546443941'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_8987ab9dfcd3c78e67c6f0243d7\``);
        await queryRunner.query(`ALTER TABLE \`img_tiendas\` DROP FOREIGN KEY \`FK_de574cc0de8f1f56c34db1dcffa\``);
        await queryRunner.query(`ALTER TABLE \`img_tiendas\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` DROP FOREIGN KEY \`FK_fea61e28ed4e34fb184461c41c3\``);
        await queryRunner.query(`ALTER TABLE \`tiendas\` DROP FOREIGN KEY \`FK_5b0a19520cde0223e62c31b03d3\``);
        await queryRunner.query(`ALTER TABLE \`tiendas\` DROP FOREIGN KEY \`FK_a10ad254b6af53bd0ae207ab13d\``);
        await queryRunner.query(`ALTER TABLE \`tiendas\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` CHANGE \`usuarios_id\` \`usuarios_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` CHANGE \`usuarios_id1\` \`usuarios_id1\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`img_productos\` DROP FOREIGN KEY \`FK_c9f6328b75c778244953e665eee\``);
        await queryRunner.query(`ALTER TABLE \`img_productos\` CHANGE \`productos_id\` \`productos_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`productos\` DROP FOREIGN KEY \`FK_3d15ed26b1a30ca6413affe2331\``);
        await queryRunner.query(`ALTER TABLE \`productos\` DROP FOREIGN KEY \`FK_ded5721b59c2820361f6cca4c33\``);
        await queryRunner.query(`ALTER TABLE \`productos\` DROP FOREIGN KEY \`FK_fbfa501f834c0bff5b73c650056\``);
        await queryRunner.query(`ALTER TABLE \`productos\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`productos\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`productos\` CHANGE \`usuarios_id\` \`usuarios_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`creditos\` DROP FOREIGN KEY \`FK_c7fc008cb8acdeb47f47d637894\``);
        await queryRunner.query(`ALTER TABLE \`creditos\` DROP FOREIGN KEY \`FK_b6614e2581874640998d489c4d1\``);
        await queryRunner.query(`ALTER TABLE \`creditos\` DROP FOREIGN KEY \`FK_c3430f966e885709d6b9202b5f7\``);
        await queryRunner.query(`ALTER TABLE \`creditos\` CHANGE \`cliente_id\` \`cliente_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`creditos\` CHANGE \`asignado_por_id\` \`asignado_por_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`creditos\` CHANGE \`estado_id\` \`estado_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` DROP FOREIGN KEY \`FK_1e538e625c181e16493c06e4533\``);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` DROP FOREIGN KEY \`FK_96412c7f7dfe5cb78ce0697dddb\``);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` DROP FOREIGN KEY \`FK_ae79da6f56e4941d1715927829c\``);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` CHANGE \`productos_id\` \`productos_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` CHANGE \`orden_compra_id\` \`orden_compra_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` DROP FOREIGN KEY \`FK_4cfd9e3adb1ca6adf6ac1089e72\``);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` DROP FOREIGN KEY \`FK_50d9cf79ba6a3544a2c11cb7eff\``);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` CHANGE \`pago_id\` \`pago_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` CHANGE \`cuota_id\` \`cuota_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` DROP FOREIGN KEY \`FK_0cd5f18cb02be0b84d0f45760ef\``);
        await queryRunner.query(`ALTER TABLE \`cuotas\` DROP FOREIGN KEY \`FK_e76012ebe36d558ebd509bd5aa7\``);
        await queryRunner.query(`ALTER TABLE \`cuotas\` CHANGE \`orden_compra_id\` \`orden_compra_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` CHANGE \`estado_id\` \`estado_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` DROP FOREIGN KEY \`FK_fb8ac0ea19b72713e9d16f26689\``);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` DROP FOREIGN KEY \`FK_b02d90c63ba84caa68d466c4bbf\``);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_c2e892466f80a97f21eb8dda4c2\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_e6da43d12293126d3473c8e1a01\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_a57aaf078609f30ed1ee347a543\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`usuarios_id\` \`usuarios_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`cuentas_cobro_id\` \`cuentas_cobro_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_51d7121c9b9257f1f49e9e12c3c\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_3ce7a12798ad630bf32e49407ad\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`referencia\` \`referencia\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`fecha_pago\` \`fecha_pago\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`orden_compra_id\` \`orden_compra_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`asignado_por_id\` \`asignado_por_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_ce3ae280065412e091a080372f5\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_2085bf8ad0172da09676fa67d76\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_ad0600ba0c3ccd924ddfd2de481\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_28de221731be7761ba1b165df08\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`apellido\` \`apellido\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`dni\` \`dni\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`contrato\` \`contrato\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`nacionalidad\` \`nacionalidad\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`barrio\` \`barrio\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`direccion\` \`direccion\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`telefono_uno\` \`telefono_uno\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`password\` \`password\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`email\` \`email\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_nacimiento\` \`fecha_nacimiento\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`mes\` \`mes\` decimal(15,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`f_prim_act\` \`f_prim_act\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`f_ult_dx\` \`f_ult_dx\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`f_ult_p\` \`f_ult_p\` varchar(45) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`ult_p\` \`ult_p\` decimal(15,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`saldo\` \`saldo\` decimal(15,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`mora\` \`mora\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`dni_tipos_id\` \`dni_tipos_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`sexos_id\` \`sexos_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`roles_id\` \`roles_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`img_tiendas\` ADD CONSTRAINT \`FK_de574cc0de8f1f56c34db1dcffa\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` ADD CONSTRAINT \`FK_fea61e28ed4e34fb184461c41c3\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` ADD CONSTRAINT \`FK_5b0a19520cde0223e62c31b03d3\` FOREIGN KEY (\`usuarios_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` ADD CONSTRAINT \`FK_a10ad254b6af53bd0ae207ab13d\` FOREIGN KEY (\`usuarios_id1\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`img_productos\` ADD CONSTRAINT \`FK_c9f6328b75c778244953e665eee\` FOREIGN KEY (\`productos_id\`) REFERENCES \`productos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos\` ADD CONSTRAINT \`FK_3d15ed26b1a30ca6413affe2331\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos\` ADD CONSTRAINT \`FK_ded5721b59c2820361f6cca4c33\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos\` ADD CONSTRAINT \`FK_fbfa501f834c0bff5b73c650056\` FOREIGN KEY (\`usuarios_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`creditos\` ADD CONSTRAINT \`FK_c7fc008cb8acdeb47f47d637894\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`creditos\` ADD CONSTRAINT \`FK_b6614e2581874640998d489c4d1\` FOREIGN KEY (\`asignado_por_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`creditos\` ADD CONSTRAINT \`FK_c3430f966e885709d6b9202b5f7\` FOREIGN KEY (\`estado_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` ADD CONSTRAINT \`FK_1e538e625c181e16493c06e4533\` FOREIGN KEY (\`productos_id\`) REFERENCES \`productos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` ADD CONSTRAINT \`FK_96412c7f7dfe5cb78ce0697dddb\` FOREIGN KEY (\`orden_compra_id\`) REFERENCES \`orden_compra\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` ADD CONSTRAINT \`FK_ae79da6f56e4941d1715927829c\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` ADD CONSTRAINT \`FK_4cfd9e3adb1ca6adf6ac1089e72\` FOREIGN KEY (\`pago_id\`) REFERENCES \`pagos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` ADD CONSTRAINT \`FK_50d9cf79ba6a3544a2c11cb7eff\` FOREIGN KEY (\`cuota_id\`) REFERENCES \`cuotas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` ADD CONSTRAINT \`FK_0cd5f18cb02be0b84d0f45760ef\` FOREIGN KEY (\`orden_compra_id\`) REFERENCES \`orden_compra\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` ADD CONSTRAINT \`FK_e76012ebe36d558ebd509bd5aa7\` FOREIGN KEY (\`estado_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` ADD CONSTRAINT \`FK_fb8ac0ea19b72713e9d16f26689\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` ADD CONSTRAINT \`FK_b02d90c63ba84caa68d466c4bbf\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_c2e892466f80a97f21eb8dda4c2\` FOREIGN KEY (\`usuarios_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_e6da43d12293126d3473c8e1a01\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_a57aaf078609f30ed1ee347a543\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_8987ab9dfcd3c78e67c6f0243d7\` FOREIGN KEY (\`cuentas_cobro_id\`) REFERENCES \`cuentas_cobro\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_51d7121c9b9257f1f49e9e12c3c\` FOREIGN KEY (\`orden_compra_id\`) REFERENCES \`orden_compra\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_3ce7a12798ad630bf32e49407ad\` FOREIGN KEY (\`asignado_por_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_ce3ae280065412e091a080372f5\` FOREIGN KEY (\`dni_tipos_id\`) REFERENCES \`dni_tipos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_2085bf8ad0172da09676fa67d76\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_ad0600ba0c3ccd924ddfd2de481\` FOREIGN KEY (\`sexos_id\`) REFERENCES \`sexos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_28de221731be7761ba1b165df08\` FOREIGN KEY (\`roles_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_28de221731be7761ba1b165df08\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_ad0600ba0c3ccd924ddfd2de481\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_2085bf8ad0172da09676fa67d76\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_ce3ae280065412e091a080372f5\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_3ce7a12798ad630bf32e49407ad\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_51d7121c9b9257f1f49e9e12c3c\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_8987ab9dfcd3c78e67c6f0243d7\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_a57aaf078609f30ed1ee347a543\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_e6da43d12293126d3473c8e1a01\``);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` DROP FOREIGN KEY \`FK_c2e892466f80a97f21eb8dda4c2\``);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` DROP FOREIGN KEY \`FK_b02d90c63ba84caa68d466c4bbf\``);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` DROP FOREIGN KEY \`FK_fb8ac0ea19b72713e9d16f26689\``);
        await queryRunner.query(`ALTER TABLE \`cuotas\` DROP FOREIGN KEY \`FK_e76012ebe36d558ebd509bd5aa7\``);
        await queryRunner.query(`ALTER TABLE \`cuotas\` DROP FOREIGN KEY \`FK_0cd5f18cb02be0b84d0f45760ef\``);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` DROP FOREIGN KEY \`FK_50d9cf79ba6a3544a2c11cb7eff\``);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` DROP FOREIGN KEY \`FK_4cfd9e3adb1ca6adf6ac1089e72\``);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` DROP FOREIGN KEY \`FK_ae79da6f56e4941d1715927829c\``);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` DROP FOREIGN KEY \`FK_96412c7f7dfe5cb78ce0697dddb\``);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` DROP FOREIGN KEY \`FK_1e538e625c181e16493c06e4533\``);
        await queryRunner.query(`ALTER TABLE \`creditos\` DROP FOREIGN KEY \`FK_c3430f966e885709d6b9202b5f7\``);
        await queryRunner.query(`ALTER TABLE \`creditos\` DROP FOREIGN KEY \`FK_b6614e2581874640998d489c4d1\``);
        await queryRunner.query(`ALTER TABLE \`creditos\` DROP FOREIGN KEY \`FK_c7fc008cb8acdeb47f47d637894\``);
        await queryRunner.query(`ALTER TABLE \`productos\` DROP FOREIGN KEY \`FK_fbfa501f834c0bff5b73c650056\``);
        await queryRunner.query(`ALTER TABLE \`productos\` DROP FOREIGN KEY \`FK_ded5721b59c2820361f6cca4c33\``);
        await queryRunner.query(`ALTER TABLE \`productos\` DROP FOREIGN KEY \`FK_3d15ed26b1a30ca6413affe2331\``);
        await queryRunner.query(`ALTER TABLE \`img_productos\` DROP FOREIGN KEY \`FK_c9f6328b75c778244953e665eee\``);
        await queryRunner.query(`ALTER TABLE \`tiendas\` DROP FOREIGN KEY \`FK_a10ad254b6af53bd0ae207ab13d\``);
        await queryRunner.query(`ALTER TABLE \`tiendas\` DROP FOREIGN KEY \`FK_5b0a19520cde0223e62c31b03d3\``);
        await queryRunner.query(`ALTER TABLE \`tiendas\` DROP FOREIGN KEY \`FK_fea61e28ed4e34fb184461c41c3\``);
        await queryRunner.query(`ALTER TABLE \`img_tiendas\` DROP FOREIGN KEY \`FK_de574cc0de8f1f56c34db1dcffa\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`roles_id\` \`roles_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`sexos_id\` \`sexos_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`dni_tipos_id\` \`dni_tipos_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`mora\` \`mora\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`saldo\` \`saldo\` decimal(15,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`ult_p\` \`ult_p\` decimal(15,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`f_ult_p\` \`f_ult_p\` varchar(45) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`f_ult_dx\` \`f_ult_dx\` varchar(45) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`f_prim_act\` \`f_prim_act\` varchar(45) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`mes\` \`mes\` decimal(15,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`fecha_nacimiento\` \`fecha_nacimiento\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`email\` \`email\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`password\` \`password\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`telefono_uno\` \`telefono_uno\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`direccion\` \`direccion\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`barrio\` \`barrio\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`nacionalidad\` \`nacionalidad\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`contrato\` \`contrato\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`dni\` \`dni\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`apellido\` \`apellido\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`nombre\` \`nombre\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_28de221731be7761ba1b165df08\` FOREIGN KEY (\`roles_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_ad0600ba0c3ccd924ddfd2de481\` FOREIGN KEY (\`sexos_id\`) REFERENCES \`sexos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_2085bf8ad0172da09676fa67d76\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_ce3ae280065412e091a080372f5\` FOREIGN KEY (\`dni_tipos_id\`) REFERENCES \`dni_tipos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`asignado_por_id\` \`asignado_por_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`orden_compra_id\` \`orden_compra_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`fecha_pago\` \`fecha_pago\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`referencia\` \`referencia\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_3ce7a12798ad630bf32e49407ad\` FOREIGN KEY (\`asignado_por_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_51d7121c9b9257f1f49e9e12c3c\` FOREIGN KEY (\`orden_compra_id\`) REFERENCES \`orden_compra\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`cuentas_cobro_id\` \`cuentas_cobro_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` CHANGE \`usuarios_id\` \`usuarios_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_a57aaf078609f30ed1ee347a543\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_e6da43d12293126d3473c8e1a01\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_c2e892466f80a97f21eb8dda4c2\` FOREIGN KEY (\`usuarios_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` ADD CONSTRAINT \`FK_b02d90c63ba84caa68d466c4bbf\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuentas_cobro\` ADD CONSTRAINT \`FK_fb8ac0ea19b72713e9d16f26689\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` CHANGE \`estado_id\` \`estado_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` CHANGE \`orden_compra_id\` \`orden_compra_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` ADD CONSTRAINT \`FK_e76012ebe36d558ebd509bd5aa7\` FOREIGN KEY (\`estado_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cuotas\` ADD CONSTRAINT \`FK_0cd5f18cb02be0b84d0f45760ef\` FOREIGN KEY (\`orden_compra_id\`) REFERENCES \`orden_compra\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` CHANGE \`cuota_id\` \`cuota_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` CHANGE \`pago_id\` \`pago_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` ADD CONSTRAINT \`FK_50d9cf79ba6a3544a2c11cb7eff\` FOREIGN KEY (\`cuota_id\`) REFERENCES \`cuotas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos_has_cuotas\` ADD CONSTRAINT \`FK_4cfd9e3adb1ca6adf6ac1089e72\` FOREIGN KEY (\`pago_id\`) REFERENCES \`pagos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` CHANGE \`orden_compra_id\` \`orden_compra_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` CHANGE \`productos_id\` \`productos_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` ADD CONSTRAINT \`FK_ae79da6f56e4941d1715927829c\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` ADD CONSTRAINT \`FK_96412c7f7dfe5cb78ce0697dddb\` FOREIGN KEY (\`orden_compra_id\`) REFERENCES \`orden_compra\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos_has_orden_compra\` ADD CONSTRAINT \`FK_1e538e625c181e16493c06e4533\` FOREIGN KEY (\`productos_id\`) REFERENCES \`productos\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`creditos\` CHANGE \`estado_id\` \`estado_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`creditos\` CHANGE \`asignado_por_id\` \`asignado_por_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`creditos\` CHANGE \`cliente_id\` \`cliente_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`creditos\` ADD CONSTRAINT \`FK_c3430f966e885709d6b9202b5f7\` FOREIGN KEY (\`estado_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`creditos\` ADD CONSTRAINT \`FK_b6614e2581874640998d489c4d1\` FOREIGN KEY (\`asignado_por_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`creditos\` ADD CONSTRAINT \`FK_c7fc008cb8acdeb47f47d637894\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos\` CHANGE \`usuarios_id\` \`usuarios_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`productos\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`productos\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`productos\` ADD CONSTRAINT \`FK_fbfa501f834c0bff5b73c650056\` FOREIGN KEY (\`usuarios_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos\` ADD CONSTRAINT \`FK_ded5721b59c2820361f6cca4c33\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`productos\` ADD CONSTRAINT \`FK_3d15ed26b1a30ca6413affe2331\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`img_productos\` CHANGE \`productos_id\` \`productos_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`img_productos\` ADD CONSTRAINT \`FK_c9f6328b75c778244953e665eee\` FOREIGN KEY (\`productos_id\`) REFERENCES \`productos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` CHANGE \`usuarios_id1\` \`usuarios_id1\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` CHANGE \`usuarios_id\` \`usuarios_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` CHANGE \`estados_id\` \`estados_id\` int UNSIGNED NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` ADD CONSTRAINT \`FK_a10ad254b6af53bd0ae207ab13d\` FOREIGN KEY (\`usuarios_id1\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` ADD CONSTRAINT \`FK_5b0a19520cde0223e62c31b03d3\` FOREIGN KEY (\`usuarios_id\`) REFERENCES \`usuarios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tiendas\` ADD CONSTRAINT \`FK_fea61e28ed4e34fb184461c41c3\` FOREIGN KEY (\`estados_id\`) REFERENCES \`estados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`img_tiendas\` CHANGE \`tiendas_id\` \`tiendas_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`img_tiendas\` ADD CONSTRAINT \`FK_de574cc0de8f1f56c34db1dcffa\` FOREIGN KEY (\`tiendas_id\`) REFERENCES \`tiendas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orden_compra\` ADD CONSTRAINT \`FK_8987ab9dfcd3c78e67c6f0243d7\` FOREIGN KEY (\`cuentas_cobro_id\`) REFERENCES \`cuentas_cobro\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
